rspec_test_one
muthumcr77/my-web-app pull request #1
Opened 2022-02-25 07:56 UTC by muthumcr77

2022-02-25 09:09 UTC, ghousemohamed requested changes

2022-02-25 09:09 UTC, ghousemohamed commented on spec/models/comment_spec.rb
> +    user = User.create!(email: "anything@io", password: "not_empty", password_confirmation: "not_empty")
Instead of using `User.create!`, you can add user.rb to factories, and do something like:

```suggestion
    user = create(:user)
```

2022-02-25 09:09 UTC, ghousemohamed commented on spec/models/comment_spec.rb
> +    subject.post = user.posts.create!(title: "anything", body: "anything_body")
Same here as well

```suggestion
    subject.post = create(:post, user_id: user.id)
```

2022-02-25 09:09 UTC, ghousemohamed commented on spec/factories/post.rb
> +    title {"title_new"}
Use this gem to generate random data -> https://github.com/faker-ruby/faker

2022-02-25 09:09 UTC, ghousemohamed commented on spec/factories/devise.rb
> +    email {"anyadmin@io"}
Use this gem to generate random data > https://github.com/faker-ruby/faker

Because everytime you need to create a user, you need a different user. Then you have to manually override email and other fields like everytime like so:

```
create(:user, email: "xxxx@xxxx.com")
```

Instead you can write something like this:

```ruby
FactoryBot.define do
  factory :user do
    email { Faker::Internet.email }
    ...
...

```

2022-02-25 09:09 UTC, ghousemohamed commented on spec/models/post_spec.rb
> +    subject.user = User.create!(email: "anything@io", password: "not_empty", password_confirmation: "not_empty")
Factory method can be used here as well, you get the idea

2022-02-25 09:09 UTC, ghousemohamed commented on spec/models/post_spec.rb
> +    post = Post.new(title: nil)
Here  you would use,

```suggestion
    post = build(:post, title: nil)
```

2022-02-25 11:44 UTC, muthumcr77 commented on spec/models/post_spec.rb
> +    post = Post.new(title: nil)
Is it the same or the latter is suggested  more?

2022-02-25 11:45 UTC, ghousemohamed commented on spec/models/post_spec.rb
> +    post = Post.new(title: nil)
the green one is the suggested line

2022-02-25 11:46 UTC, muthumcr77 commented on spec/models/post_spec.rb
> +    post = Post.new(title: nil)
Oh its like in the controller? Same method?

2022-02-25 11:47 UTC, muthumcr77 commented on spec/models/post_spec.rb
> +    subject.user = User.create!(email: "anything@io", password: "not_empty", password_confirmation: "not_empty")
Yep. Got it.

2022-02-25 11:49 UTC, ghousemohamed commented on spec/models/post_spec.rb
> +    post = Post.new(title: nil)
`build` is a method from factorybot, you have to use that

2022-02-27 06:56 UTC, muthumcr77 commented on spec/models/post_spec.rb
> +    post = Post.new(title: nil)
Cool.

2022-03-11 05:13 UTC, closed without merging